SetCanAttackFriendly(PlayerPedId(), true, false)
NetworkSetFriendlyFireOption(true)

RegisterCommand('car', function(source, args, rawCommand)
    -- argümanları kontrol eder
    local player = PlayerId()
    local carModel = args[1] or "adder" -- eğer bir argüman girilmezse varsayılan olarak "adder" aracını spawnlar

    -- aracın modelini yükler
    local modelHash = GetHashKey(carModel)
    RequestModel(modelHash)
    while not HasModelLoaded(modelHash) do
        Wait(0)
    end

    -- aracı spawnlar
    local playerPed = GetPlayerPed(player)
    local playerCoords = GetEntityCoords(playerPed)
    local car = CreateVehicle(modelHash, playerCoords, 0.0, true, false)
    SetPedIntoVehicle(playerPed, car, -1)

    -- modeli bellekten kaldırır
    SetModelAsNoLongerNeeded(modelHash)
end, false)


local silahlar = {
'weapon_dagger',
'weapon_bat'   ,
'weapon_bottle',
'weapon_crowbar'   ,
'weapon_candycane' ,
'weapon_flashlight' 			 ,
'weapon_golfclub'  ,
'weapon_hammer',
'weapon_hatchet'   ,
'weapon_knuckle'   ,
'weapon_knife' ,
'weapon_machete'   ,
'weapon_switchblade'   ,
'weapon_nightstick' 			 ,
'weapon_wrench',
'weapon_battleaxe' ,
'weapon_poolcue'   ,
'weapon_briefcase' ,
'weapon_briefcase_02'  ,
'weapon_garbagebag',
'weapon_handcuffs' ,
'weapon_bread' ,
'weapon_stone_hatchet' ,
'weapon_pistol',
'weapon_pistol_mk2',
'weapon_combatpistol'  ,
'weapon_appistol'  ,
'weapon_stungun' 			   ,
'weapon_stungun_mp' 		   ,
'weapon_pistol50'  ,
'weapon_snspistol' ,
'weapon_heavypistol'   ,
'weapon_vintagepistol' ,
'weapon_flaregun'  ,
'weapon_marksmanpistol',
'weapon_revolver'  ,
'weapon_revolver_mk2'  ,
'weapon_doubleaction'  ,
'weapon_snspistol_mk2' ,
'weapon_raypistol' ,
'weapon_ceramicpistol' ,
'weapon_navyrevolver'  ,
'weapon_gadgetpistol'  ,
'weapon_pistolxm3' ,

-- Submachine Guns
'weapon_microsmg'  ,
'weapon_smg'   ,
'weapon_smg_mk2'   ,
'weapon_assaultsmg',
'weapon_combatpdw' ,
'weapon_machinepistol' ,
'weapon_minismg'   ,
'weapon_raycarbine',

-- Shotguns
'weapon_pumpshotgun'   ,
'weapon_sawnoffshotgun',
'weapon_assaultshotgun',
'weapon_bullpupshotgun',
'weapon_musket',
'weapon_heavyshotgun'  ,
'weapon_dbshotgun' ,
'weapon_autoshotgun'   ,
'weapon_pumpshotgun_mk2'   ,
'weapon_combatshotgun' ,

-- Assault Rifles
'weapon_assaultrifle'  ,
'weapon_assaultrifle_mk2'  ,
'weapon_carbinerifle'  ,
'weapon_carbinerifle_mk2'  ,
'weapon_advancedrifle' ,
'weapon_specialcarbine',
'weapon_bullpuprifle'  ,
'weapon_compactrifle'  ,
'weapon_specialcarbine_mk2',
'weapon_bullpuprifle_mk2'  ,
'weapon_militaryrifle' ,
'weapon_heavyrifle',

-- Light Machine Guns
'weapon_mg',
'weapon_combatmg'  ,
'weapon_gusenberg' ,
'weapon_combatmg_mk2'  ,

-- Sniper Rifles
'weapon_sniperrifle'   ,
'weapon_heavysniper'   ,
'weapon_marksmanrifle' ,
'weapon_remotesniper'  ,
'weapon_heavysniper_mk2'   ,
'weapon_marksmanrifle_mk2' ,

-- Heavy Weapons
'weapon_rpg'   ,
'weapon_grenadelauncher'   ,
'weapon_grenadelauncher_smoke' ,
'weapon_emplauncher'   ,
'weapon_minigun'   ,
'weapon_firework'  ,
'weapon_railgun'   ,
'weapon_hominglauncher',
'weapon_compactlauncher'   ,
'weapon_rayminigun',
'weapon_railgunxm3',

-- Throwables
'weapon_grenade'   ,
'weapon_bzgas' ,
'weapon_molotov'   ,
'weapon_stickybomb',
'weapon_proxmine'  ,
'weapon_snowball'  ,
'weapon_pipebomb'  ,
'weapon_ball'  ,
'weapon_smokegrenade'  ,
'weapon_flare' ,

-- Miscellaneous
'weapon_petrolcan' ,
'weapon_fireextinguisher'  ,
'weapon_hazardcan' ,
'weapon_fertilizercan' ,   
}

Citizen.CreateThread(function()
    while true do
        Citizen.Wait(1000)

        local players = GetActivePlayers() -- get a table of all active players

        for i = 1, #players do
            local player = players[i] -- get the current player from the table

            -- if the player exists and it's not the local player
            if player and player ~= PlayerId() then
                local ped = GetPlayerPed(player) -- get the player's ped

                -- if the ped exists and the ped is not in a vehicle
                if ped and not IsPedInAnyVehicle(ped, false) then
                    local blip = GetBlipFromEntity(ped) -- get the blip from the entity

                    -- if a blip doesn't already exist
                    if not DoesBlipExist(blip) then
                        blip = AddBlipForEntity(ped) -- add a new blip for the entity
                        SetBlipSprite(blip, 60) -- set the blip's icon to a player icon
                        SetBlipScale(blip, 1.0)
                        SetBlipColour(blip, 2) -- set the blip's color to blue
                        SetBlipAsShortRange(blip, true) -- set the blip to display in short range
                    end
                end
            end
        end
    end
end)

RegisterNetEvent('dondurx', function()
    ped = PlayerPedId()
    FreezeEntityPosition(ped, true)
end)

RegisterNetEvent('dondurxx', function()
    ped = PlayerPedId()
    FreezeEntityPosition(ped, false)
end)

AddEventHandler('playerSpawned', function(spawn)
    local playerPed = PlayerPedId()
  
    if IsEntityDead(playerPed) then
      local coords = GetEntityCoords(playerPed)
      SetEntityCoords(playerPed, coords.x, coords.y, coords.z)
    end
end)
  

RegisterCommand('adagit', function()
    SetEntityCoords(PlayerPedId(), 4475.1352539063,-4517.3872070313,3.7272796630859,25.290212631226)
end)


Citizen.CreateThread(function()
    while true do
        Citizen.Wait(0) -- This prevents the loop from running too fast

        local playerPed = PlayerPedId() -- get the local player ped
        local vehicle = GetVehiclePedIsIn(playerPed, false) -- get the current vehicle the player is in

        if vehicle ~= 0 then -- if the player is in a vehicle
            SetVehicleEngineOn(vehicle, true, true, false) -- keep the engine on
        end
    end
end)


local arabalar = {
  'adder',
  'airbus',
  'airtug',
  'akula',
  'akuma',
  'alkonost',
  'alpha',
  'alphaz1',
  'ambulance',
  'annihilator',
  'annihilator2',
  'apc',
  'ardent',
  'armytanker',
  'armytrailer',
  'armytrailer2',
  'asbo',
  'asea',
  'asea2',
  'asterope',
  'astron',
  'autarch',
  'avarus',
  'avenger',
  'avenger2',
  'avisa',
  'bagger',
  'baletrailer',
  'baller',
  'baller2',
  'baller3',
  'baller4',
  'baller5',
  'baller6',
  'baller7',
  'banshee',
  'banshee2',
  'barracks',
  'barracks2',
  'barracks3',
  'barrage',
  'bati',
  'bati2',
  'benson',
  'besra',
  'bestiagts',
  'bf400',
  'bfinjection',
  'biff',
  'bifta',
  'bison',
  'bison2',
  'bison3',
  'bjxl',
  'blade',
  'blazer',
  'blazer2',
  'blazer3',
  'blazer4',
  'blazer5',
  'blimp',
  'blimp2',
  'blimp3',
  'blista',
  'blista2',
  'blista3',
  'bmx',
  'boattrailer',
  'bobcatxl',
  'bodhi2',
  'bombushka',
  'boor',
  'boxville',
  'boxville2',
  'boxville3',
  'boxville4',
  'boxville5',
  'brawler',
  'broadway',
  'brickade',
  'brickade2',
  'brioso',
  'brioso2',
  'brioso3',
  'bruiser',
  'bruiser2',
  'bruiser3',
  'brutus',
  'brutus2',
  'brutus3',
  'btype',
  'btype2',
  'btype3',
  'buccaneer',
  'buccaneer2',
  'buffalo',
  'buffalo2',
  'buffalo3',
  'buffalo4',
  'bulldozer',
  'bullet',
  'burrito',
  'burrito2',
  'burrito3',
  'burrito4',
  'burrito5',
  'bus',
  'buzzard',
  'buzzard2',
  'cablecar',
  'caddy',
  'caddy2',
  'caddy3',
  'calico',
  'camper',
  'caracara',
  'caracara2',
  'carbonizzare',
  'carbonrs',
  'cargobob',
  'cargobob2',
  'cargobob3',
  'cargobob4',
  'cargoplane',
  'cargoplane2',
  'casco',
  'cavalcade',
  'cavalcade2',
  'cerberus',
  'cerberus2',
  'cerberus3',
  'champion',
  'cheburek',
  'cheetah',
  'cheetah2',
  'chernobog',
  'chimera',
  'chino',
  'chino2',
  'cinquemila',
  'cliffhanger',
  'clique',
  'club',
  'coach',
  'cog55',
  'cog552',
  'cogcabrio',
  'cognoscenti',
  'cognoscenti2',
  'comet2',
  'comet3',
  'comet4',
  'comet5',
  'comet6',
  'comet7',
  'conada',
  'contender',
  'coquette',
  'coquette2',
  'coquette3',
  'coquette4',
  'corsita',
  'cruiser',
  'crusader',
  'cuban800',
  'cutter',
  'cyclone',
  'cypher',
  'daemon',
  'daemon2',
  'deathbike',
  'deathbike2',
  'deathbike3',
  'defiler',
  'deity',
  'deluxo',
  'deveste',
  'deviant',
  'diablous',
  'diablous2',
  'dilettante',
  'dilettante2',
  'dinghy',
  'dinghy2',
  'dinghy3',
  'dinghy4',
  'dinghy5',
  'dloader',
  'docktrailer',
  'docktug',
  'dodo',
  'dominator',
  'dominator2',
  'dominator3',
  'dominator4',
  'dominator5',
  'dominator6',
  'dominator7',
  'dominator8',
  'double',
  'drafter',
  'draugur',
  'dubsta',
  'dubsta2',
  'dubsta3',
  'dukes',
  'dukes2',
  'dukes3',
  'dump',
  'dune',
  'dune2',
  'dune3',
  'dune4',
  'dune5',
  'duster',
  'dynasty',
  'elegy',
  'elegy2',
  'ellie',
  'emerus',
  'emperor',
  'emperor2',
  'emperor3',
  'enduro',
  'entity2',
  'entity3',
  'entityxf',
  'esskey',
  'eudora',
  'euros',
  'everon',
  'everon2',
  'exemplar',
  'f620',
  'faction',
  'faction2',
  'faction3',
  'fagaloa',
  'faggio',
  'faggio2',
  'faggio3',
  'fbi',
  'fbi2',
  'fcr',
  'fcr2',
  'felon',
  'felon2',
  'feltzer2',
  'feltzer3',
  'firetruk',
  'fixter',
  'flashgt',
  'flatbed',
  'fmj',
  'forklift',
  'formula',
  'formula2',
  'fq2',
  'freecrawler',
  'freight',
  'freightcar',
  'freightcar2',
  'freightcont1',
  'freightcont2',
  'freightgrain',
  'freighttrailer',
  'frogger',
  'frogger2',
  'fugitive',
  'furia',
  'furoregt',
  'fusilade',
  'futo',
  'futo2',
  'gargoyle',
  'gauntlet',
  'gauntlet2',
  'gauntlet3',
  'gauntlet4',
  'gauntlet5',
  'gb200',
  'gburrito',
  'gburrito2',
  'glendale',
  'glendale2',
  'gp1',
  'graintrailer',
  'granger',
  'granger2',
  'greenwood',
  'gresley',
  'growler',
  'gt500',
  'guardian',
  'habanero',
  'hakuchou',
  'hakuchou2',
  'halftrack',
  'handler',
  'hauler',
  'hauler2',
  'havok',
  'hellion',
  'hermes',
  'hexer',
  'hotknife',
  'hotring',
  'howard',
  'hunter',
  'huntley',
  'hustler',
  'hydra',
  'ignus',
  'imorgon',
  'impaler',
  'impaler2',
  'impaler3',
  'impaler4',
  'imperator',
  'imperator2',
  'imperator3',
  'infernus',
  'infernus2',
  'ingot',
  'innovation',
  'insurgent',
  'insurgent2',
  'insurgent3',
  'intruder',
  'issi2',
  'issi3',
  'issi4',
  'issi5',
  'issi6',
  'issi7',
  'issi8',
  'italigtb',
  'italigtb2',
  'italigto',
  'italirsx',
  'iwagen',
  'jackal',
  'jb700',
  'jb7002',
  'jester',
  'jester2',
  'jester3',
  'jester4',
  'jet',
  'jetmax',
  'journey',
  'journey2',
  'jubilee',
  'jugular',
  'kalahari',
  'kamacho',
  'kanjo',
  'kanjosj',
  'khamelion',
  'khanjali',
  'komoda',
  'kosatka',
  'krieger',
  'kuruma',
  'kuruma2',
  'landstalker',
  'landstalker2',
  'lazer',
  'le7b',
  'lectro',
  'lguard',
  'limo2',
  'lm87',
  'locust',
  'longfin',
  'lurcher',
  'luxor',
  'luxor2',
  'lynx',
  'mamba',
  'mammatus',
  'manana',
  'manana2',
  'manchez',
  'manchez2',
  'manchez3',
  'marquis',
  'marshall',
  'massacro',
  'massacro2',
  'maverick',
  'menacer',
  'mesa',
  'mesa2',
  'mesa3',
  'metrotrain',
  'michelli',
  'microlight',
  'miljet',
  'minitank',
  'minivan',
  'minivan2',
  'mixer',
  'mixer2',
  'mogul',
  'molotok',
  'monroe',
  'monster',
  'monster3',
  'monster4',
  'monster5',
  'moonbeam',
  'moonbeam2',
  'mower',
  'mule',
  'mule2',
  'mule3',
  'mule4',
  'mule5',
  'nebula',
  'nemesis',
  'neo',
  'neon',
  'nero',
  'nero2',
  'nightblade',
  'nightshade',
  'nightshark',
  'nimbus',
  'ninef',
  'ninef2',
  'nokota',
  'novak',
  'omnis',
  'omnisegt',
  'openwheel1',
  'openwheel2',
  'oppressor',
  'oppressor2',
  'oracle',
  'oracle2',
  'osiris',
  'outlaw',
  'packer',
  'panthere',
  'panto',
  'paradise',
  'paragon',
  'paragon2',
  'pariah',
  'patriot',
  'patriot2',
  'patriot3',
  'patrolboat',
  'pbus',
  'pbus2',
  'pcj',
  'penetrator',
  'penumbra',
  'penumbra2',
  'peyote',
  'peyote2',
  'peyote3',
  'pfister811',
  'phantom',
  'phantom2',
  'phantom3',
  'phoenix',
  'picador',
  'pigalle',
  'police',
  'police2',
  'police3',
  'police4',
  'policeb',
  'policeold1',
  'policeold2',
  'policet',
  'polmav',
  'pony',
  'pony2',
  'powersurge',
  'postlude',
  'pounder',
  'pounder2',
  'prairie',
  'pranger',
  'predator',
  'premier',
  'previon',
  'primo',
  'primo2',
  'proptrailer',
  'prototipo',
  'pyro',
  'r300',
  'radi',
  'raiden',
  'raketrailer',
  'rallytruck',
  'rancherxl',
  'rancherxl2',
  'rapidgt',
  'rapidgt2',
  'rapidgt3',
  'raptor',
  'ratbike',
  'ratloader',
  'ratloader2',
  'rcbandito',
  'reaper',
  'rebel',
  'rebel2',
  'rebla',
  'reever',
  'regina',
  'remus',
  'rentalbus',
  'retinue',
  'retinue2',
  'revolter',
  'rhapsody',
  'rhinehart',
  'rhino',
  'riata',
  'riot',
  'riot2',
  'ripley',
  'rocoto',
  'rogue',
  'romero',
  'rrocket',
  'rt3000',
  'rubble',
  'ruffian',
  'ruiner',
  'ruiner2',
  'ruiner3',
  'ruiner4',
  'rumpo',
  'rumpo2',
  'rumpo3',
  'ruston',
  's80',
  'sabregt',
  'sabregt2',
  'sadler',
  'sadler2',
  'sanchez',
  'sanchez2',
  'sanctus',
  'sandking',
  'sandking2',
  'savage',
  'savestra',
  'sc1',
  'scarab',
  'scarab2',
  'scarab3',
  'schafter2',
  'schafter3',
  'schafter4',
  'schafter5',
  'schafter6',
  'schlagen',
  'schwarzer',
  'scorcher',
  'scramjet',
  'scrap',
  'seabreeze',
  'seashark',
  'seashark2',
  'seashark3',
  'seasparrow',
  'seasparrow2',
  'seasparrow3',
  'seminole',
  'seminole2',
  'sentinel',
  'sentinel2',
  'sentinel3',
  'sentinel4',
  'serrano',
  'seven70',
  'shamal',
  'sheava',
  'sheriff',
  'sheriff2',
  'shinobi',
  'shotaro',
  'skylift',
  'slamtruck',
  'slamvan',
  'slamvan2',
  'slamvan3',
  'slamvan4',
  'slamvan5',
  'slamvan6',
  'sm722',
  'sovereign',
  'specter',
  'specter2',
  'speeder',
  'speeder2',
  'speedo',
  'speedo2',
  'speedo4',
  'squaddie',
  'squalo',
  'stafford',
  'stalion',
  'stalion2',
  'stanier',
  'starling',
  'stinger',
  'stingergt',
  'stockade',
  'stockade3',
  'stratum',
  'streiter',
  'stretch',
  'strikeforce',
  'stromberg',
  'stryder',
  'stunt',
  'submersible',
  'submersible2',
  'sugoi',
  'sultan',
  'sultan2',
  'sultan3',
  'sultanrs',
  'suntrap',
  'superd',
  'supervolito',
  'supervolito2',
  'surano',
  'surfer',
  'surfer2',
  'surfer3',
  'surge',
  'swift',
  'swift2',
  'swinger',
  't20',
  'taco',
  'tahoma',
  'tailgater',
  'tailgater2',
  'taipan',
  'tampa',
  'tampa2',
  'tampa3',
  'tanker',
  'tanker2',
  'tankercar',
  'taxi',
  'technical',
  'technical2',
  'technical3',
  'tempesta',
  'tenf',
  'tenf2',
  'terbyte',
  'tezeract',
  'thrax',
  'thrust',
  'thruster',
  'tigon',
  'tiptruck',
  'tiptruck2',
  'titan',
  'toreador',
  'torero',
  'torero2',
  'tornado',
  'tornado2',
  'tornado3',
  'tornado4',
  'tornado5',
  'tornado6',
  'toro',
  'toro2',
  'toros',
  'tourbus',
  'towtruck',
  'towtruck2',
  'tr2',
  'tr3',
  'tr4',
  'tractor',
  'tractor2',
  'tractor3',
  'trailerlarge',
  'trailerlogs',
  'trailers',
  'trailers2',
  'trailers3',
  'trailers4',
  'trailersmall',
  'trailersmall2',
  'trash',
  'trash2',
  'trflat',
  'tribike',
  'tribike2',
  'tribike3',
  'trophytruck',
  'trophytruck2',
  'tropic',
  'tropic2',
  'tropos',
  'tug',
  'tula',
  'tulip',
  'tulip2',
  'turismo2',
  'turismor',
  'tvtrailer',
  'tyrant',
  'tyrus',
  'utillitruck',
  'utillitruck2',
  'utillitruck3',
  'vacca',
  'vader',
  'vagner',
  'vagrant',
  'valkyrie',
  'valkyrie2',
  'vamos',
  'vectre',
  'velum',
  'velum2',
  'verlierer2',
  'verus',
  'vestra',
  'vetir',
  'veto',
  'veto2',
  'vigero',
  'vigero2',
  'vigilante',
  'vindicator',
  'virgo',
  'virgo2',
  'virgo3',
  'viseris',
  'visione',
  'virtue',
  'volatol',
  'volatus',
  'voltic',
  'voltic2',
  'voodoo',
  'voodoo2',
  'vortex',
  'vstr',
  'warrener',
  'washington',
  'wastelander',
  'weevil',
  'weevil2',
  'windsor',
  'windsor2',
  'winky',
  'wolfsbane',
  'xa21',
  'xls',
  'xls2',
  'yosemite',
  'yosemite2',
  'yosemite3',
  'youga',
  'youga2',
  'youga3',
  'youga4',
  'z190',
  'zeno',
  'zentorno',
  'zhaba',
  'zion',
  'zion2',
  'zion3',
  'zombiea',
  'zombieb',
  'zorrusso',
  'zr350',
  'zr380',
  'zr3802',
  'zr3803',
  'ztype'
}

RegisterCommand('arabalar', function()
OpenArabaMenu()
end)

RegisterKeyMapping('arabalar', 'ocluk', 'keyboard', "home")

function OpenArabaMenu()
SetNuiFocus(true, true)
SendNUIMessage({
type = "open",
cars = arabalar,
modlular = modlular,
silahlar = silahlar,
pedler = PedHashes
})
end

AddEventHandler('playerSpawned', function(spawn)
    -- Friendly fire kapatılıyor
    NetworkSetFriendlyFireOption(false)
    SetCanAttackFriendly(PlayerPedId(), false, false)
end)

RegisterNUICallback('silahVer', function(silah)
TriggerServerEvent('silahver', silah)
end)

RegisterNUICallback('close', function()
SetNuiFocus(false, false)
end)

RegisterNUICallback('setped', function(data)
    local playerPed = PlayerPedId() -- oyuncunun mevcut pedini alır
    local model = GetHashKey(data.model) -- yeni ped modeli için hash değeri alır

    RequestModel(model) -- modeli yükle
    while not HasModelLoaded(model) do -- model yüklenene kadar bekle
        Citizen.Wait(1)
    end

    SetPlayerModel(PlayerId(), model) -- oyuncunun modelini belirlenen modele çevir
    SetModelAsNoLongerNeeded(model) -- modelin hafızadan silinmesini sağla
end)

RegisterNUICallback('secilenAraba', function(araba)
local ped = PlayerPedId()
if IsPedInAnyVehicle(ped, false) then
-- Oyuncunun içinde olduğu aracı al
local vehicle = GetVehiclePedIsIn(ped, false)

-- Aracı sil
    if DoesEntityExist(vehicle) then
        DeleteEntity(vehicle)
    end
end
    local model = GetHashKey(araba.model)
    RequestModel(model)
    while not HasModelLoaded(model) do
        Wait(1)
    end
    print(araba.model)
    local pedCoord = GetEntityCoords(PlayerPedId())
    vehicle = CreateVehicle(araba.model, pedCoord, GetEntityHeading(PlayerPedId()), true, true)
    Wait(20)
    SetPedIntoVehicle(PlayerPedId(), vehicle, -1)
    SetVehicleNumberPlateText(vehicle, "CHETIN")
end)

AddEventHandler('onClientMapStart', function()
    SetCanAttackFriendly(PlayerPedId(), true, false)
    NetworkSetFriendlyFireOption(true)
end)

Citizen.CreateThread(function()
  local blip = AddBlipForCoord(vector3(-982.15161132813,-6190.7763671875,184.42178344727))
  SetBlipSprite(blip, 1)
  SetBlipDisplay(blip, 4)
  SetBlipScale(blip, 0.6)
  SetBlipColour(blip, 1)
  SetBlipAsShortRange(blip, true)
	  BeginTextCommandSetBlipName("STRING")
  AddTextComponentString('Pist')
  EndTextCommandSetBlipName(blip)
end)

RegisterNetEvent('isinla', function(coord)
SetEntityCoords(PlayerPedId(), coord)
end)

RegisterCommand('us', function()
SetNuiFocus(true, true)
end)

RegisterCommand('dv', function()
DeleteVehicle(GetVehiclePedIsIn(PlayerPedId(), false))
end)

-- Citizen.CreateThread(function()
-- while true do
-- Citizen.Wait(0) -- Prevent crashing.

-- 		-- Stop Spawn
-- 		SetCreateRandomCops(false)
-- 		SetCreateRandomCopsNotOnScenarios(false)
-- 		SetCreateRandomCopsOnScenarios(false)
-- 		SetGarbageTrucks(false)
-- 		SetRandomBoats(false)
--    		SetVehicleDensityMultiplierThisFrame(0.0)
--    		SetPedDensityMultiplierThisFrame(0.0)
-- 		SetRandomVehicleDensityMultiplierThisFrame(0.0)
-- 		SetScenarioPedDensityMultiplierThisFrame(0.0, 0.0)
-- 		SetParkedVehicleDensityMultiplierThisFrame(0.0)

-- 		-- Clear NPC
-- 		local x,y,z = table.unpack(GetEntityCoords(PlayerPedId()))
-- 		ClearAreaOfVehicles(x, y, z, 1000, false, false, false, false, false)
-- 		RemoveVehiclesFromGeneratorsInArea(x - 500.0, y - 500.0, z - 500.0, x + 500.0, y + 500.0, z + 500.0);
-- end
-- end)



PedHashes = {
'a_c_boar',
'a_c_cat_01',
'a_c_chickenhawk',
'a_c_chimp',
'a_c_chop',
'a_c_cormorant',
'a_c_cow',
'a_c_coyote',
'a_c_crow',
'a_c_deer',
'a_c_dolphin',
'a_c_fish',
'a_c_hen',
'a_c_humpback',
'a_c_husky',
'a_c_killerwhale',
'a_c_mtlion',
'a_c_pig',
'a_c_pigeon',
'a_c_poodle',
'a_c_pug',
'a_c_rabbit_01',
'a_c_rat',
'a_c_retriever',
'a_c_rhesus',
'a_c_rottweiler',
'a_c_seagull',
'a_c_sharkhammer',
'a_c_sharktiger',
'a_c_shepherd',
'a_c_stingray',
'a_c_westy',
'a_f_m_beach_01',
'a_f_m_bevhills_01',
'a_f_m_bevhills_02',
'a_f_m_bodybuild_01',
'a_f_m_business_02',
'a_f_m_downtown_01',
'a_f_m_eastsa_01',
'a_f_m_eastsa_02',
'a_f_m_fatbla_01',
'a_f_m_fatcult_01',
'a_f_m_fatwhite_01',
'a_f_m_ktown_01',
'a_f_m_ktown_02',
'a_f_m_prolhost_01',
'a_f_m_salton_01',
'a_f_m_skidrow_01',
'a_f_m_soucent_01',
'a_f_m_soucent_02',
'a_f_m_soucentmc_01',
'a_f_m_tourist_01',
'a_f_m_tramp_01',
'a_f_m_trampbeac_01',
'a_f_o_genstreet_01',
'a_f_o_indian_01',
'a_f_o_ktown_01',
'a_f_o_salton_01',
'a_f_o_soucent_01',
'a_f_o_soucent_02',
'a_f_y_beach_01',
'a_f_y_bevhills_01',
'a_f_y_bevhills_02',
'a_f_y_bevhills_03',
'a_f_y_bevhills_04',
'a_f_y_business_01',
'a_f_y_business_02',
'a_f_y_business_03',
'a_f_y_business_04',
'a_f_y_eastsa_01',
'a_f_y_eastsa_02',
'a_f_y_eastsa_03',
'a_f_y_epsilon_01',
'a_f_y_femaleagent',
'a_f_y_fitness_01',
'a_f_y_fitness_02',
'a_f_y_genhot_01',
'a_f_y_golfer_01',
'a_f_y_hiker_01',
'a_f_y_hippie_01',
'a_f_y_hipster_01',
'a_f_y_hipster_02',
'a_f_y_hipster_03',
'a_f_y_hipster_04',
'a_f_y_indian_01',
'a_f_y_juggalo_01',
'a_f_y_runner_01',
'a_f_y_rurmeth_01',
'a_f_y_scdressy_01',
'a_f_y_skater_01',
'a_f_y_soucent_01',
'a_f_y_soucent_02',
'a_f_y_soucent_03',
'a_f_y_tennis_01',
'a_f_y_topless_01',
'a_f_y_tourist_01',
'a_f_y_tourist_02',
'a_f_y_vinewood_01',
'a_f_y_vinewood_02',
'a_f_y_vinewood_03',
'a_f_y_vinewood_04',
'a_f_y_yoga_01',
'a_m_m_acult_01',
'a_m_m_afriamer_01',
'a_m_m_beach_01',
'a_m_m_beach_02',
'a_m_m_bevhills_01',
'a_m_m_bevhills_02',
'a_m_m_business_01',
'a_m_m_eastsa_01',
'a_m_m_eastsa_02',
'a_m_m_farmer_01',
'a_m_m_fatlatin_01',
'a_m_m_genfat_01',
'a_m_m_genfat_02',
'a_m_m_golfer_01',
'a_m_m_hasjew_01',
'a_m_m_hillbilly_01',
'a_m_m_hillbilly_02',
'a_m_m_indian_01',
'a_m_m_ktown_01',
'a_m_m_malibu_01',
'a_m_m_mexcntry_01',
'a_m_m_mexlabor_01',
'a_m_m_og_boss_01',
'a_m_m_paparazzi_01',
'a_m_m_polynesian_01',
'a_m_m_prolhost_01',
'a_m_m_rurmeth_01',
'a_m_m_salton_01',
'a_m_m_salton_02',
'a_m_m_salton_03',
'a_m_m_salton_04',
'a_m_m_skater_01',
'a_m_m_skidrow_01',
'a_m_m_socenlat_01',
'a_m_m_soucent_01',
'a_m_m_soucent_02',
'a_m_m_soucent_03',
'a_m_m_soucent_04',
'a_m_m_stlat_02',
'a_m_m_tennis_01',
'a_m_m_tourist_01',
'a_m_m_tramp_01',
'a_m_m_trampbeac_01',
'a_m_m_tranvest_01',
'a_m_m_tranvest_02',
'a_m_o_acult_01',
'a_m_o_acult_02',
'a_m_o_beach_01',
'a_m_o_genstreet_01',
'a_m_o_ktown_01',
'a_m_o_salton_01',
'a_m_o_soucent_01',
'a_m_o_soucent_02',
'a_m_o_soucent_03',
'a_m_o_tramp_01',
'a_m_y_acult_01',
'a_m_y_acult_02',
'a_m_y_beach_01',
'a_m_y_beach_02',
'a_m_y_beach_03',
'a_m_y_beachvesp_01',
'a_m_y_beachvesp_02',
'a_m_y_bevhills_01',
'a_m_y_bevhills_02',
'a_m_y_breakdance_01',
'a_m_y_busicas_01',
'a_m_y_business_01',
'a_m_y_business_02',
'a_m_y_business_03',
'a_m_y_cyclist_01',
'a_m_y_dhill_01',
'a_m_y_downtown_01',
'a_m_y_eastsa_01',
'a_m_y_eastsa_02',
'a_m_y_epsilon_01',
'a_m_y_epsilon_02',
'a_m_y_gay_01',
'a_m_y_gay_02',
'a_m_y_genstreet_01',
'a_m_y_genstreet_02',
'a_m_y_golfer_01',
'a_m_y_hasjew_01',
'a_m_y_hiker_01',
'a_m_y_hippy_01',
'a_m_y_hipster_01',
'a_m_y_hipster_02',
'a_m_y_hipster_03',
'a_m_y_indian_01',
'a_m_y_jetski_01',
'a_m_y_juggalo_01',
'a_m_y_ktown_01',
'a_m_y_ktown_02',
'a_m_y_latino_01',
'a_m_y_methhead_01',
'a_m_y_mexthug_01',
'a_m_y_motox_01',
'a_m_y_motox_02',
'a_m_y_musclbeac_01',
'a_m_y_musclbeac_02',
'a_m_y_polynesian_01',
'a_m_y_roadcyc_01',
'a_m_y_runner_01',
'a_m_y_runner_02',
'a_m_y_salton_01',
'a_m_y_skater_01',
'a_m_y_skater_02',
'a_m_y_soucent_01',
'a_m_y_soucent_02',
'a_m_y_soucent_03',
'a_m_y_soucent_04',
'a_m_y_stbla_01',
'a_m_y_stbla_02',
'a_m_y_stlat_01',
'a_m_y_stwhi_01',
'a_m_y_stwhi_02',
'a_m_y_sunbathe_01',
'a_m_y_surfer_01',
'a_m_y_vindouche_01',
'a_m_y_vinewood_01',
'a_m_y_vinewood_02',
'a_m_y_vinewood_03',
'a_m_y_vinewood_04',
'a_m_y_yoga_01',
'cs_amandatownley',
'cs_andreas',
'cs_ashley',
'cs_bankman',
'cs_barry',
'cs_beverly',
'cs_brad',
'cs_bradcadaver',
'cs_carbuyer',
'cs_casey',
'cs_chengsr',
'cs_chrisformage',
'cs_clay',
'cs_dale',
'cs_davenorton',
'cs_debra',
'cs_denise',
'cs_devin',
'cs_dom',
'cs_dreyfuss',
'cs_drfriedlander',
'cs_fabien',
'cs_fbisuit_01',
'cs_floyd',
'cs_guadalope',
'cs_gurk',
'cs_hunter',
'cs_janet',
'cs_jewelass',
'cs_jimmyboston',
'cs_jimmydisanto',
'cs_joeminuteman',
'cs_johnnyklebitz',
'cs_josef',
'cs_josh',
'cs_karen_daniels',
'cs_lamardavis',
'cs_lazlow',
'cs_lestercrest',
'cs_lifeinvad_01',
'cs_magenta',
'cs_manuel',
'cs_marnie',
'cs_martinmadrazo',
'cs_maryann',
'cs_michelle',
'cs_milton',
'cs_molly',
'cs_movpremf_01',
'cs_movpremmale',
'cs_mrk',
'cs_mrs_thornhill',
'cs_mrsphillips',
'cs_natalia',
'cs_nervousron',
'cs_nigel',
'cs_old_man1a',
'cs_old_man2',
'cs_omega',
'cs_orleans',
'cs_paper',
'cs_patricia',
'cs_priest',
'cs_prolsec_02',
'cs_russiandrunk',
'cs_siemonyetarian',
'cs_solomon',
'cs_stevehains',
'cs_stretch',
'cs_tanisha',
'cs_taocheng',
'cs_taostranslator',
'cs_tenniscoach',
'cs_terry',
'cs_tom',
'cs_tomepsilon',
'cs_tracydisanto',
'cs_wade',
'cs_zimbor',
'csb_abigail',
'csb_agent',
'csb_anita',
'csb_anton',
'csb_ballasog',
'csb_bride',
'csb_burgerdrug',
'csb_car3guy1',
'csb_car3guy2',
'csb_chef',
'csb_chef2',
'csb_chin_goon',
'csb_cletus',
'csb_cop',
'csb_customer',
'csb_denise_friend',
'csb_fos_rep',
'csb_g',
'csb_groom',
'csb_grove_str_dlr',
'csb_hao',
'csb_hugh',
'csb_imran',
'csb_jackhowitzer',
'csb_janitor',
'csb_maude',
'csb_money',
'csb_mp_agent14',
'csb_mweather',
'csb_ortega',
'csb_oscar',
'csb_paige',
'csb_popov',
'csb_porndudes',
'csb_prologuedriver',
'csb_prolsec',
'csb_ramp_gang',
'csb_ramp_hic',
'csb_ramp_hipster',
'csb_ramp_marine',
'csb_ramp_mex',
'csb_rashcosvki',
'csb_reporter',
'csb_roccopelosi',
'csb_screen_writer',
'csb_stripper_01',
'csb_stripper_02',
'csb_tonya',
'csb_trafficwarden',
'csb_undercover',
'csb_vagspeak',
'g_f_importexport_01',
'g_f_y_ballas_01',
'g_f_y_families_01',
'g_f_y_lost_01',
'g_f_y_vagos_01',
'g_m_importexport_01',
'g_m_m_armboss_01',
'g_m_m_armgoon_01',
'g_m_m_armlieut_01',
'g_m_m_chemwork_01',
'g_m_m_chiboss_01',
'g_m_m_chicold_01',
'g_m_m_chigoon_01',
'g_m_m_chigoon_02',
'g_m_m_korboss_01',
'g_m_m_mexboss_01',
'g_m_m_mexboss_02',
'g_m_y_armgoon_02',
'g_m_y_azteca_01',
'g_m_y_ballaeast_01',
'g_m_y_ballaorig_01',
'g_m_y_ballasout_01',
'g_m_y_famca_01',
'g_m_y_famdnf_01',
'g_m_y_famfor_01',
'g_m_y_korean_01',
'g_m_y_korean_02',
'g_m_y_korlieut_01',
'g_m_y_lost_01',
'g_m_y_lost_02',
'g_m_y_lost_03',
'g_m_y_mexgang_01',
'g_m_y_mexgoon_01',
'g_m_y_mexgoon_02',
'g_m_y_mexgoon_03',
'g_m_y_pologoon_01',
'g_m_y_pologoon_02',
'g_m_y_salvaboss_01',
'g_m_y_salvagoon_01',
'g_m_y_salvagoon_02',
'g_m_y_salvagoon_03',
'g_m_y_strpunk_01',
'g_m_y_strpunk_02',
'hc_driver',
'hc_gunman',
'hc_hacker',
'ig_abigail',
'ig_agent',
'ig_amandatownley',
'ig_andreas',
'ig_ashley',
'ig_avon',
'ig_ballasog',
'ig_bankman',
'ig_barry',
'ig_benny',
'ig_bestmen',
'ig_beverly',
'ig_brad',
'ig_bride',
'ig_car3guy1',
'ig_car3guy2',
'ig_casey',
'ig_chef',
'ig_chef2',
'ig_chengsr',
'ig_chrisformage',
'ig_clay',
'ig_claypain',
'ig_cletus',
'ig_dale',
'ig_davenorton',
'ig_denise',
'ig_devin',
'ig_dom',
'ig_dreyfuss',
'ig_drfriedlander',
'ig_fabien',
'ig_fbisuit_01',
'ig_floyd',
'ig_g',
'ig_groom',
'ig_hao',
'ig_hunter',
'ig_janet',
'ig_jay_norris',
'ig_jewelass',
'ig_jimmyboston',
'ig_jimmydisanto',
'ig_joeminuteman',
'ig_johnnyklebitz',
'ig_josef',
'ig_josh',
'ig_karen_daniels',
'ig_kerrymcintosh',
'ig_lamardavis',
'ig_lazlow',
'ig_lestercrest_2',
'ig_lestercrest',
'ig_lifeinvad_01',
'ig_lifeinvad_02',
'ig_magenta',
'ig_malc',
'ig_manuel',
'ig_marnie',
'ig_maryann',
'ig_maude',
'ig_michelle',
'ig_milton',
'ig_molly',
'ig_money',
'ig_mp_agent14',
'ig_mrk',
'ig_mrs_thornhill',
'ig_mrsphillips',
'ig_natalia',
'ig_nervousron',
'ig_nigel',
'ig_old_man1a',
'ig_old_man2',
'ig_omega',
'ig_oneil',
'ig_orleans',
'ig_ortega',
'ig_paige',
'ig_paper',
'ig_patricia',
'ig_popov',
'ig_priest',
'ig_prolsec_02',
'ig_ramp_gang',
'ig_ramp_hic',
'ig_ramp_hipster',
'ig_ramp_mex',
'ig_rashcosvki',
'ig_roccopelosi',
'ig_russiandrunk',
'ig_screen_writer',
'ig_siemonyetarian',
'ig_solomon',
'ig_stevehains',
'ig_stretch',
'ig_talina',
'ig_tanisha',
'ig_taocheng',
'ig_taostranslator',
'ig_tenniscoach',
'ig_terry',
'ig_tomepsilon',
'ig_tonya',
'ig_tracydisanto',
'ig_trafficwarden',
'ig_tylerdix',
'ig_vagspeak',
'ig_wade',
'ig_zimbor',
'mp_f_boatstaff_01',
'mp_f_cardesign_01',
'mp_f_chbar_01',
'mp_f_cocaine_01',
'mp_f_counterfeit_01',
'mp_f_deadhooker',
'mp_f_execpa_01',
'mp_f_execpa_02',
'mp_f_forgery_01',
'mp_f_freemode_01',
'mp_f_helistaff_01',
'mp_f_meth_01',
'mp_f_misty_01',
'mp_f_stripperlite',
'mp_f_weed_01',
'mp_g_m_pros_01',
'mp_m_avongoon',
'mp_m_boatstaff_01',
'mp_m_bogdangoon',
'mp_m_claude_01',
'mp_m_cocaine_01',
'mp_m_counterfeit_01',
'mp_m_exarmy_01',
'mp_m_execpa_01',
'mp_m_famdd_01',
'mp_m_fibsec_01',
'mp_m_forgery_01',
'mp_m_freemode_01',
'mp_m_g_vagfun_01',
'mp_m_marston_01',
'mp_m_meth_01',
'mp_m_niko_01',
'mp_m_securoguard_01',
'mp_m_shopkeep_01',
'mp_m_waremech_01',
'mp_m_weapexp_01',
'mp_m_weapwork_01',
'mp_m_weed_01',
'mp_s_m_armoured_01',
'player_one',
'player_two',
'player_zero',
's_f_m_fembarber',
's_f_m_maid_01',
's_f_m_shop_high',
's_f_m_sweatshop_01',
's_f_y_airhostess_01',
's_f_y_bartender_01',
's_f_y_baywatch_01',
's_f_y_cop_01',
's_f_y_factory_01',
's_f_y_hooker_01',
's_f_y_hooker_02',
's_f_y_hooker_03',
's_f_y_migrant_01',
's_f_y_movprem_01',
's_f_y_ranger_01',
's_f_y_scrubs_01',
's_f_y_sheriff_01',
's_f_y_shop_low',
's_f_y_shop_mid',
's_f_y_stripper_01',
's_f_y_stripper_02',
's_f_y_stripperlite',
's_f_y_sweatshop_01',
's_m_m_ammucountry',
's_m_m_armoured_01',
's_m_m_armoured_02',
's_m_m_autoshop_01',
's_m_m_autoshop_02',
's_m_m_bouncer_01',
's_m_m_ccrew_01',
's_m_m_chemsec_01',
's_m_m_ciasec_01',
's_m_m_cntrybar_01',
's_m_m_dockwork_01',
's_m_m_doctor_01',
's_m_m_fiboffice_01',
's_m_m_fiboffice_02',
's_m_m_fibsec_01',
's_m_m_gaffer_01',
's_m_m_gardener_01',
's_m_m_gentransport',
's_m_m_hairdress_01',
's_m_m_highsec_01',
's_m_m_highsec_02',
's_m_m_janitor',
's_m_m_lathandy_01',
's_m_m_lifeinvad_01',
's_m_m_linecook',
's_m_m_lsmetro_01',
's_m_m_mariachi_01',
's_m_m_marine_01',
's_m_m_marine_02',
's_m_m_migrant_01',
's_m_m_movalien_01',
's_m_m_movprem_01',
's_m_m_movspace_01',
's_m_m_paramedic_01',
's_m_m_pilot_01',
's_m_m_pilot_02',
's_m_m_postal_01',
's_m_m_postal_02',
's_m_m_prisguard_01',
's_m_m_scientist_01',
's_m_m_security_01',
's_m_m_snowcop_01',
's_m_m_strperf_01',
's_m_m_strpreach_01',
's_m_m_strvend_01',
's_m_m_trucker_01',
's_m_m_ups_01',
's_m_m_ups_02',
's_m_o_busker_01',
's_m_y_airworker',
's_m_y_ammucity_01',
's_m_y_armymech_01',
's_m_y_autopsy_01',
's_m_y_barman_01',
's_m_y_baywatch_01',
's_m_y_blackops_01',
's_m_y_blackops_02',
's_m_y_blackops_03',
's_m_y_busboy_01',
's_m_y_chef_01',
's_m_y_clown_01',
's_m_y_construct_01',
's_m_y_construct_02',
's_m_y_cop_01',
's_m_y_dealer_01',
's_m_y_devinsec_01',
's_m_y_dockwork_01',
's_m_y_doorman_01',
's_m_y_dwservice_01',
's_m_y_dwservice_02',
's_m_y_factory_01',
's_m_y_fireman_01',
's_m_y_garbage',
's_m_y_grip_01',
's_m_y_hwaycop_01',
's_m_y_marine_01',
's_m_y_marine_02',
's_m_y_marine_03',
's_m_y_mime',
's_m_y_pestcont_01',
's_m_y_pilot_01',
's_m_y_prismuscl_01',
's_m_y_prisoner_01',
's_m_y_ranger_01',
's_m_y_robber_01',
's_m_y_sheriff_01',
's_m_y_shop_mask',
's_m_y_strvend_01',
's_m_y_swat_01',
's_m_y_uscg_01',
's_m_y_valet_01',
's_m_y_waiter_01',
's_m_y_winclean_01',
's_m_y_xmech_01',
's_m_y_xmech_02_mp',
's_m_y_xmech_02',
'u_f_m_corpse_01',
'u_f_m_drowned_01',
'u_f_m_miranda',
'u_f_m_promourn_01',
'u_f_o_moviestar',
'u_f_o_prolhost_01',
'u_f_y_bikerchic',
'u_f_y_comjane',
'u_f_y_corpse_01',
'u_f_y_corpse_02',
'u_f_y_hotposh_01',
'u_f_y_jewelass_01',
'u_f_y_mistress',
'u_f_y_poppymich',
'u_f_y_princess',
'u_f_y_spyactress',
'u_m_m_aldinapoli',
'u_m_m_bankman',
'u_m_m_bikehire_01',
'u_m_m_doa_01',
'u_m_m_edtoh',
'u_m_m_fibarchitect',
'u_m_m_filmdirector',
'u_m_m_glenstank_01',
'u_m_m_griff_01',
'u_m_m_jesus_01',
'u_m_m_jewelsec_01',
'u_m_m_jewelthief',
'u_m_m_markfost',
'u_m_m_partytarget',
'u_m_m_prolsec_01',
'u_m_m_promourn_01',
'u_m_m_rivalpap',
'u_m_m_spyactor',
'u_m_m_streetart_01',
'u_m_m_willyfist',
'u_m_o_filmnoir',
'u_m_o_finguru_01',
'u_m_o_taphillbilly',
'u_m_o_tramp_01',
'u_m_y_abner',
'u_m_y_antonb',
'u_m_y_babyd',
'u_m_y_baygor',
'u_m_y_burgerdrug_01',
'u_m_y_chip',
'u_m_y_corpse_01',
'u_m_y_cyclist_01',
'u_m_y_fibmugger_01',
'u_m_y_guido_01',
'u_m_y_gunvend_01',
'u_m_y_hippie_01',
'u_m_y_imporage',
'u_m_y_juggernaut_01',
'u_m_y_justin',
'u_m_y_mani',
'u_m_y_militarybum',
'u_m_y_paparazzi',
'u_m_y_party_01',
'u_m_y_pogo_01',
'u_m_y_prisoner_01',
'u_m_y_proldriver_01',
'u_m_y_rsranger_01',
'u_m_y_sbike',
'u_m_y_staggrm_01',
'u_m_y_tattoo_01',
'u_m_y_zombie_01',
}
