silahlar = {
  'weapon_dagger',
  'weapon_bat'   ,
  'weapon_bottle',
  'weapon_crowbar'   ,
  'weapon_candycane' ,
  'weapon_flashlight' 			 ,
  'weapon_golfclub'  ,
  'weapon_hammer',
  'weapon_hatchet'   ,
  'weapon_knuckle'   ,
  'weapon_knife' ,
  'weapon_machete'   ,
  'weapon_switchblade'   ,
  'weapon_nightstick' 			 ,
  'weapon_wrench',
  'weapon_battleaxe' ,
  'weapon_poolcue'   ,
  'weapon_briefcase' ,
  'weapon_briefcase_02'  ,
  'weapon_garbagebag',
  'weapon_handcuffs' ,
  'weapon_bread' ,
  'weapon_stone_hatchet' ,
  'weapon_pistol',
  'weapon_pistol_mk2',
  'weapon_combatpistol'  ,
  'weapon_appistol'  ,
  'weapon_stungun' 			   ,
  'weapon_stungun_mp' 		   ,
  'weapon_pistol50'  ,
  'weapon_snspistol' ,
  'weapon_heavypistol'   ,
  'weapon_vintagepistol' ,
  'weapon_flaregun'  ,
  'weapon_marksmanpistol',
  'weapon_revolver'  ,
  'weapon_revolver_mk2'  ,
  'weapon_doubleaction'  ,
  'weapon_snspistol_mk2' ,
  'weapon_raypistol' ,
  'weapon_ceramicpistol' ,
  'weapon_navyrevolver'  ,
  'weapon_gadgetpistol'  ,
  'weapon_pistolxm3' ,

  -- Submachine Guns
  'weapon_microsmg'  ,
  'weapon_smg'   ,
  'weapon_smg_mk2'   ,
  'weapon_assaultsmg',
  'weapon_combatpdw' ,
  'weapon_machinepistol' ,
  'weapon_minismg'   ,
  'weapon_raycarbine',

  -- Shotguns
  'weapon_pumpshotgun'   ,
  'weapon_sawnoffshotgun',
  'weapon_assaultshotgun',
  'weapon_bullpupshotgun',
  'weapon_musket',
  'weapon_heavyshotgun'  ,
  'weapon_dbshotgun' ,
  'weapon_autoshotgun'   ,
  'weapon_pumpshotgun_mk2'   ,
  'weapon_combatshotgun' ,

  -- Assault Rifles
  'weapon_assaultrifle'  ,
  'weapon_assaultrifle_mk2'  ,
  'weapon_carbinerifle'  ,
  'weapon_carbinerifle_mk2'  ,
  'weapon_advancedrifle' ,
  'weapon_specialcarbine',
  'weapon_bullpuprifle'  ,
  'weapon_compactrifle'  ,
  'weapon_specialcarbine_mk2',
  'weapon_bullpuprifle_mk2'  ,
  'weapon_militaryrifle' ,
  'weapon_heavyrifle',

  -- Light Machine Guns
  'weapon_mg',
  'weapon_combatmg'  ,
  'weapon_gusenberg' ,
  'weapon_combatmg_mk2'  ,

  -- Sniper Rifles
  'weapon_sniperrifle'   ,
  'weapon_heavysniper'   ,
  'weapon_marksmanrifle' ,
  'weapon_remotesniper'  ,
  'weapon_heavysniper_mk2'   ,
  'weapon_marksmanrifle_mk2' ,

  -- Heavy Weapons
  'weapon_rpg'   ,
  'weapon_grenadelauncher'   ,
  'weapon_grenadelauncher_smoke' ,
  'weapon_emplauncher'   ,
  'weapon_minigun'   ,
  'weapon_firework'  ,
  'weapon_railgun'   ,
  'weapon_hominglauncher',
  'weapon_compactlauncher'   ,
  'weapon_rayminigun',
  'weapon_railgunxm3',

  -- Throwables
  'weapon_grenade'   ,
  'weapon_bzgas' ,
  'weapon_molotov'   ,
  'weapon_stickybomb',
  'weapon_proxmine'  ,
  'weapon_snowball'  ,
  'weapon_pipebomb'  ,
  'weapon_ball'  ,
  'weapon_smokegrenade'  ,
  'weapon_flare' ,

  -- Miscellaneous
  'weapon_petrolcan' ,
  'weapon_fireextinguisher'  ,
  'weapon_hazardcan' ,
  'weapon_fertilizercan' ,   
}
